### PR TITLE
Fix debts

### LINKED ISSUE #13: Code debts in tracker screen.
Code debts in tracker screen, inline styles are defined at multiple places.
1. Modify and reduce them wherever possible
2. Calender option at the top of screen takes too long to load, identify the cause the resolve.

_Originally posted by @Ruthvik-1411 in https://github.com/Ruthvik-1411/Finance_Tracker_app/pull/12#pullrequestreview-2190029052_

### PR DESCRIPTION
**Pull request by Ruthvik-1411**
Resolves #13 

Changelog:

1. Tracker screen:
    * Debts: 
       * The inline styles made the code difficult to read, so added them in the stylesheets for better view and reusability.
    * Responsiveness:
      * It is observed that the tracker screen is slow compared to other screens and datepicker constantly gets stuck or difficult to invoke.
      * Changes:
          1. Optimize state updates: Updated the functions to use the callback methods to make the state updates and useEffect dependencies reduce latency
          2. Excessive re-renders: The preious useEffect component for victoryChart renders the chart multiple times to display the animation style. Modified it to use, requestAnimationFrame and useRef to remove unnecessary re-renders. This has improved the performance by a lot.
   * Added the loading option to call backend api when month/year is changed and limited date selection to past dates only.

2. Add expense screen also has style debts, fixed them as it has some similarity with tracker screen. Added conditional checks for mandatory components in the form and display corresponding alert to user.
3. Prettify other screens.

### CODE REVIEW

File: screens/TrackerScreen.js [hunk 1]
```diff
@@ -36,215 +44,193 @@ const TrackerScreen = () => {
...
+          <View style={styles.chartTitlestyle}>
+            <Text style={styles.chartTitle}>Analysis</Text>
           </View>
-          <View
+          <VictoryPie
+            data={[
+              { x: "Hobbies", y: 350 },
+              { x: "Entertainment", y: 400 },
+              { x: "Travel", y: 550 },
+              { x: "Food", y: 800 },
```
Comment (Ruthvik-1411) [inline screens/TrackerScreen.js:164]: Can have one single data source or variable that is parsed to multiple components in the screen. As the idea is to fetch all the data in a single api call, this would be better in future when backend is fulfilled. The data source will have the budget data, chart data as well.
